# site properties and page defaults
title: Feifei Chen's Homepage

# subtitle: Soft Robotics Lab
description: An engaging 1-3 sentence description of your lab.
header: images/background3.jpg
footer: images/background3.jpg
#  slider
iis_slider_array: []
# site social media and other links
links:
  email: ffchen@sjtu.edu.cn
  orcid: 0000-0001-6733-1259
  google-scholar: mlDNufQAAAAJ

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
