- id: doi:10.1109/TMECH.2021.3071394
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/3516/9515346/9397352/chen1-3071394-large.gif
  title: Topology Optimization of Skeleton-Reinforced Soft Pneumatic Actuators for Desired Motions
  authors:
  - Shitong Chen
  - Feifei Chen
  - Zizheng Cao
  - Yusheng Wang
  - Yunpeng Miao
  - Guoying Gu
  - Xiangyang Zhu
  publisher: IEEE/ASME Transactions on Mechatronics 
  date: '2021-04-06'
  link: https://ieeexplore.ieee.org/abstract/document/9397352
  description: We present a design paradigm for soft pneumatic multimaterial actuators by incorporating a stiffer material layer as a skeleton to softer inflated rubber. A topology optimization-based framework is used to automatically generate the skeleton layout, enabling desired motions like bending or twisting. Our approach considers geometric and material nonlinearities, achieving high-performance bending (73°) and twisting (143°) actuators. The design methodology offers a rigorous and efficient solution for generating material layouts that deliver spatially varying deformation upon actuation.
  


- id: 10.1109/TRO.2019.2920108
  title: Automatic Design of Soft Dielectric Elastomer Actuators With Optimal Spatial Electric Fields
  authors:
  - Feifei Chen
  - Kun Liu
  - Yiqiang Wang
  - Jiang Zou
  - Guoying Gu
  - Xiangyang Zhu
  publisher: IEEE Transactions on Robotics 
  date: '2019-06-20'
  link: https://ieeexplore.ieee.org/abstract/document/8742767
  description: Dielectric elastomer actuators (DEAs) are a promising actuation technology in soft robotics owing to their large voltage-induced deformation and rapid response. In this paper, we present an automatic design methodology to maximize the concerned displacement(s) of DEAs by topology optimization of the applied spatial electric fields (SEFs). We implement our method for motions of single and multiple degrees of freedom (DOFs) of planar DEAs, and the optimized SEFs have been found to improve the output displacements by more than 75% compared with their intuitive counterparts. Overall, our paper represents the first step toward automatic design of soft DEAs for diverse potential applications in soft machines and robots.
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/8860/8855036/8742767/gu11-2920108-large.gif

- id: 10.3390/polym12030619
  title: A Unidirectional Soft Dielectric Elastomer Actuator Enabled by Built-In Honeycomb Metastructures
  authors:
  - Kun Liu
  - Shitong Chen
  - Feifei Chen
  - Xiangyang Zhu
  publisher: Polymers 
  date: '2020-03-09'
  link: https://www.mdpi.com/2073-4360/12/3/619
  description: The programmable actuation of DEAs along a predefined direction is challenging. In this paper, we provide an innovative solution to this problem by harnessing honeycomb metastructures to program the mechanical behavior of dielectric elastomers. To achieve uniaxial actuation and maximize its magnitude, we develop a finite element analysis model and study how the prestretch ratios and the honeycomb structuring tailor the voltage-induced deformation. We also provide a scalable fabrication solution by directly printing honeycomb lattices made of thermoplastic polyurethane on dielectric membranes with natural bonding. The preliminary experiments demonstrate that our designed DEA is able to undergo unidirectional motion, with the nominal strain reaching up to 15.8%.
  image: https://www.mdpi.com/polymers/polymers-12-00619/article_deploy/html/images/polymers-12-00619-g001.png

- id: 10.1109/TMECH.2020.3043883
  title: An Integrated Design and Fabrication Strategy for Planar Soft Dielectric Elastomer Actuators
  authors:
  - Feifei Chen
  - Kun Liu
  - Qi Pan
  - Shitong Chen
  - Xiangyang Zhu
  publisher: IEEE/ASME Transactions on Mechatronics 
  date: '2020-12-10'
  link: https://ieeexplore.ieee.org/abstract/document/9290427
  description: we present an integrated design strategy for planar DEAs, aiming to realize their full potential. To endow the actuator module with the maximal actuation strain, we carry out dimensionless analysis to identify the key design variables, develop a fast finite element analysis model, and thoroughly investigate how the geometric structuring and the material prestretch tailor the voltage-induced deformation. The experiments show that the optimized actuator obtains a remarkable nominal strain up to 38.6%. We also characterize the dynamic performance of the optimized actuator, evaluate its energy density and power density, and develop a soft locomotion robot that can crawl through a confined tunnel, at a fast moving speed up to 0.17 body length/s.
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/3516/9570750/9290427/chen1-3043883-large.gif

- id: 10.1109/LRA.2022.3143292
  title: Triply Periodic Channels Enable Soft Pneumatic Linear Actuator With Single Material and Scalability
  authors:
  - Feifei Chen
  - Yunpeng Miao
  - Lei Zhang
  - Shitong Chen
  - Xiangyang Zhu
  publisher: IEEE Robotics and Automation Letters
  date: '2022-1-14'
  link: https://ieeexplore.ieee.org/document/9682555
  description: In this letter, we propose a new class of soft pneumatic linear actuators based on periodic curved air channels. These actuators exhibit single-material, uniaxial deformation, high energy density, and scalability. The shape of the channels is parameterized by modified triply periodic minimal surfaces (mTPMS), which partition the space into two intertwined sub-domains of open-cell topology. By adjusting the period ratio of the mTPMS, the actuators can deliver linear, areal, and volumetric actuation modes. The focus of this letter is on investigating the linear motion mode. We develop a finite element model and perform parametric optimization to predict and improve the actuator's deformation behavior. The mTPMS-based actuators, 3D printed with complex geometries, demonstrate linear motions with significant strain, high blocking force, and impressive energy density. We also showcase the application of these linear actuators as artificial muscles in an antagonistic arrangement. This research contributes to the integrated design of pneumatic metamaterials and represents a significant advancement in the concept of "materials as machines" for various scale applications.
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/7083369/9647862/9682555/chen1-3143292-large.gif

- id: 10.1109/LRA.2021.3072813
  title: Soft Twisting Pneumatic Actuators Enabled by Freeform Surface Design
  authors:
  - Feifei Chen
  - Yunpeng Miao
  - Guoying Gu
  - Xiangyang Zhu
  publisher: IEEE Robotics and Automation Letters
  date: '2021-04-13'
  link: https://ieeexplore.ieee.org/document/9403872
  description: We propose a new class of soft twisting pneumatic actuators that purely rely on the freeform chamber geometry to achieve large bi-directional twisting rotations. The freeform chamber surface integrates geometric flexibility in the cross section, lateral profile, and axial chirality, which are parameterized as design variables. We develop a finite element analysis model and investigate the effect of the geometry parameters on the actuators' mechanical behavior. This letter represents an important step toward leveraging the full potential of the freeform geometry design to create novel compact soft-bodied actuators and robots.
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/7083369/9399748/9403872/chen5-3072813-large.gif

- id: 10.1039/D0TB01585G
  title: Stimuli-responsive functional materials for soft robotics
  authors:
  - Zequn Shen
  - Feifei Chen
  - Xiangyang Zhu
  - Ken-Tye Yong
  - Guoying Gu
  publisher: Journal of Materials Chemistry B
  date: '2020-08-18'
  link: https://pubs.rsc.org/en/content/articlelanding/2020/TB/D0TB01585G
  description: Functional materials have spurred the advancement of soft robotics with the potential to perform safe interactions and adaptative functions in unstructured environments. We review the development of stimuli-responsive functional materials particularly used for soft robotic systems. This review covers five representative types of soft stimuli-responsive functional materials, namely (i) dielectric elastomers, (ii) hydrogels, (iii) shape memory polymers, (iv) liquid crystal elastomers, and (v) magnetic materials, with focuses on their inherent material properties, working mechanisms, and design strategies for actuation and sensing. We also highlight the state-of-the-art applications of soft stimuli-responsive functional materials in locomotion robots, grippers and sensors. Finally, we summarize the current challenges and map out future trends for engineering next-generation functional materials for soft robotics.
  image: https://pubs.rsc.org/image/article/2020/tb/d0tb01585g/d0tb01585g-f1.gif

- id: 10.1007/s11431-022-2346-6
  title: Tailoring the in-plane and out-of-plane stiffness of soft fingers by endoskeleton topology optimization for stable grasping
  authors:
  - DeChen LI
  - ShiTong CHEN
  - ZeNan SONG
  - JiaLong LIANG
  - XiangYang ZHU
  - FeiFei CHEN
  publisher: SCIENCE CHINA Technological Sciences
  date: '2023-05-24'
  link: https://www.sciengine.com/SCTS/doi/10.1007/s11431-022-2346-6
  description: Current soft grippers usually focus on the in-plane large deformation and load capacity but ignore the effect of out-of-plane external loads, which may lead to instability in practical scenarios. In this paper, we design a new type of soft finger by embedding an endoskeleton inside the widely-used Pneu-Nets actuator, and the endoskeleton layout is optimized to achieve a remarkable bending deflection and limited lateral deflection under combined external in-plane and out-of-plane loads. Static and dynamic experiment results validate that the soft gripper with endoskeleton embedded exhibits remarkably improved out-of-plane stiffness, without sacrificing the in-plane bending flexibility, and leads to more stable grasping.
  image: https://www.sciengine.com/figures/figures-3eb52119610144809cf1b44a636852da-scts-2022-1189-t5.png


- id: 10.1007/s11431-021-1920-y
  title: Enhancing Interaction Performance of Soft Pneumatic-networks Grippers by Skeleton Topology Optimization.
  authors:
  - ShiTong Chen
  - YuSheng Wang
  - DeChen Li
  - FeiFei Chen
  - XiangYang Zhu
  publisher: Science China Technological Sciences
  date: '2021-11-12'
  link: https://www.sciengine.com/SCTS/doi/10.1007/s11431-021-1920-y
  description:  by the dexterity of human hands, we propose a computational design framework for soft grippers with a focus on improving their interaction performance in power grasping or precision grasping mode. The design paradigm rests on attaching a relatively stiffer skeleton layer to the parametric pneumatic networks based actuator which is widely used due to the geometric advantage, and the skeleton layout is designed for customized interaction conditions by a level set based topology optimization approach. As expected, the optimized skeleton layouts exhibit specified structural features highly relevant to the predefined concentrated loads for precision grip or distributed loads for power grip, which physically implies the compromise between deformability and stiffness. This work represents an initial step toward the rational design for interaction in soft robots.

  image: https://www.sciengine.com/figures/figures-c0cc89a5917845669edb27a163eea12c-scts-2021-0641-t5.png


- id: 10.1089/soro.2019.0105
  title: Design, Modeling, and Evaluation of Fabric-Based Pneumatic Actuators for Soft Wearable Assistive Gloves
  authors:
  - Lisen Ge
  - Feifei Chen
  - Dong Wang
  - Yifan Zhang
  - Dong Han
  - Tao Wang
  - Guoying Gu
  publisher: Soft Robotics
  date: '2020-01-29'
  link: https://www.liebertpub.com/doi/10.1089/soro.2019.0105
  description: We present the design, modeling, and evaluation of a class of soft fabric-based pneumatic actuators (SFPAs) for soft wearable assistive gloves that can simultaneously assist the thumb abduction and finger flexion and extension motions for brachial plexus injury patients. We investigate the mechanical behaviors of various woven fabrics and rib weft-knitted fabric structures, guiding us to design a thumb-abduction SFPA, a finger-flexion SFPA, and a finger-extension SFPA. We further develop a mathematical model to evaluate the influence of the geometric parameters on the blocked tip forces of the finger-flexion SFPAs and extension torques of the finger-extension SFPAs. We then integrate our SFPAs into a soft wearable assistive glove with a portable control system. The clinical evaluation results demonstrate the effectiveness of our designed glove in assisting hand motions and grasping tasks.

  image: https://www.liebertpub.com/cms/10.1089/soro.2019.0105/asset/images/medium/soro.2019.0105_figure10.jpg

- id: 10.1109/TMECH.2023.3322585
  title: Soft Robotic Joints With Anisotropic Stiffness by Multiobjective Topology Optimization
  authors:
  - Shitong Chen
  - Guozhen Zhou
  - Dechen Li
  - Zenan Song
  - Feifei Chen
  publisher: IEEE/ASME Transactions on Mechatronics 
  date: '2023-10-25'
  link: https://ieeexplore.ieee.org/document/10296179
  description: Soft robots, inspired by compliant mechanisms, offer advantages like frictionless operation and monolithic fabrication. However, current designs often neglect stiffness characteristics in directions beyond the pursued motion, limiting practical use. This article introduces soft robotic joints with anisotropic stiffness, achieved through multi-objective topology optimization. Three basic joints—elongation, twisting, and omnidirectional bending—are automated in design. Quantitative characterization reveals improved stiffness against disturbances. Demonstrating a dexterous wrist-hand system and cable-driven fingers, the joints enable practical active motions while effectively withstanding unexpected disturbances, enhancing their applicability in confined spaces.
  image: "../images/publications/shitongchen.png"
  
- id: 10.1109/TRO.2023.3323825
  title: Morphological Design for Pneumatic Soft Actuators and Robots With Desired Deformation Behavior
  authors:
  - Feifei Chen
  - Zenan Song
  - Shitong Chen
  - Guoying Gu 
  - Xiangyang Zhu
  publisher: IEEE Transactions on Robotics 
  date: '2023-10-25'
  link: https://ieeexplore.ieee.org/document/10296178
  description: This article introduces an integrated approach for shaping pneumatic soft actuators or robots with a homogeneous structure, allowing complex motions with a simple input pressure. The design framework leverages B-splines for freeform boundary surfaces, employing nonlinear mechanics and shape derivative-based optimization. It navigates the high-dimensional design space while regulating surface quality through geometric constraints. External forces and interactions are considered, broadening applicability to load-capacity pursuit. Computational efficiency is enhanced through trust region suboptimization, utilizing gradient information for displacement-dependent objective functions. The approach is validated across various applications, demonstrating capabilities for extension, bending, twisting motions, and continuous robot arms with in-plane and out-of-plane configurations. Multiple chamber designs for diverse deformation behaviors are also addressed through co-optimization of morphological shape and air pressures.
  image: https://ieeexplore.ieee.org/mediastore_new/IEEE/content/media/8860/10352149/10296178/chen12-3323825-large.gif

- id: 10.1007/s11431-023-2451-x
  title: Optimal biaxial prestretch ratios of soft dielectric elastomer actuators for maximal voltage-induced displacement
  authors:
  - Kai Luo
  - JiaNing Wu
  - FeiFei Chen
  publisher: SCIENCE CHINA Technological Sciences
  date: '2023-09-20'
  link: https://link.springer.com/article/10.1007/s11431-023-2451-x
  description: This paper addresses the challenge of determining optimal prestretch ratios for voltage-induced deformation in dielectric elastomer actuators (DEAs). Lacking efficient design methods, the traditional approach involves time-consuming experiments. The authors propose a quantitative optimization framework, integrating Lagrange method and adjoint sensitivity analysis to consider DEA's nonlinearities and complex electromechanical coupling. The derivative of the displacement field with respect to prestretch ratios enables efficient gradient-based optimization. The method is validated on planar DEAs and free-standing three-dimensional DEMES, demonstrating significant improvements in displacements compared to non-optimized designs in both simulations and experiments.
  image: "../images/publications/kailuo.jpg"

- id: 10.1007/978-981-99-6492-5_13
  title: Modeling and Design Optimization of a Pre-stretched Rolled Dielectric Elastomer Actuator
  authors:
  - Jianing Wu
  - Kai Luo
  - Peinan Yan
  - Xiazhi Hu
  - Huangwei Ji
  - FeiFei Chen
  publisher: International Conference on Intelligent Robotics and Applications
  date: '2023-10-16'
  link: https://link.springer.com/chapter/10.1007/978-981-99-6492-5_13
  description: This paper introduces a high-performance actuator composed of a rolled dielectric elastomer actuator (DEA) connected in series with a spring for pre-stretching. A simplified static model of the rolled DEA is established to predict its mechanical behavior under various conditions. The optimal pre-stretch effect is achieved through a two-dimensional search for the optimal combination of spring stiffness and pre-stretch, maximizing free displacement, blocking force, or equivalent work. Experimental validation demonstrates significant improvements in free displacement and blocking force compared to a springless structure. The study provides valuable insights into enhancing rolled DEAs' performance, showcasing potential applications in soft robotics.
  image: "../images/publications/jianingwu.png"